name: EasierMC-NewInv
description: This plugin is just meant to add some simple machines which makes Minecraft much easier.
version: 1.0.3
author: bwfcwalshy
main: com.bwfcwalshy.easiermcnewinv.EasierMC
commands:
  recipe:
    description: Recipe command
  newmc:
    description: Main command